apiVersion: v2
name: dummy-app
description: A Helm chart for dummy application deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - dummy
  - demo
  - nodejs

maintainers:
  - name: DevOps Team
    email: devops@example.com

sources:
  - https://github.com/Zalfsten/github
