name: Enforce PR Labels

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  enforce-labels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    
    steps:
      - name: Check for version labels
        run: |
          LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"
          
          if [[ "$LABELS" == *"major version"* ]] || [[ "$LABELS" == *"minor version"* ]] || [[ "$LABELS" == *"patch version"* ]]; then
            echo "✅ Version label found!"
            
            # Check that only one version label is present
            version_count=0
            if [[ "$LABELS" == *"major version"* ]]; then
              version_count=$((version_count + 1))
            fi
            if [[ "$LABELS" == *"minor version"* ]]; then
              version_count=$((version_count + 1))
            fi
            if [[ "$LABELS" == *"patch version"* ]]; then
              version_count=$((version_count + 1))
            fi
            
            if [[ $version_count -gt 1 ]]; then
              echo "❌ Multiple version labels found! Please use only one version label."
              exit 1
            fi
            
            echo "Version label validation passed!"
          else
            echo "❌ No version label found!"
            echo "Please add one of the following labels to your PR:"
            echo "- major version (for breaking changes)"
            echo "- minor version (for new features)"
            echo "- patch version (for bug fixes)"
            exit 1
          fi